#!/bin/bash

if [ -n $1 ]; then
    ln -sf $1 link.frag
fi

errcol=$(tput bold; tput setaf 1)
warncol=$(tput setaf 2)
normal=$(tput sgr0)

killall a.out &> /dev/null
# make clean 
rm a.out

jep=`echo -e '\001'`

echo compile
make -j2 2>&1  \
	| sed -le 's/^.*] //g' 	\
	| egrep --line-buffered --color '.*\h:[0-9]*|*dbg|debug|.*\c:[0-9]*|*.*\cpp:[0-9]*|Warning|warning|WARNING|ERROR|error|Error$' 


echo run

## turn off vsync
export vblank_mode=0

## record 
#  parec -d alsa_output.pci-0000_00_1f.3.analog-stereo.monitor --file-format=wav test.wav
#  parec -d alsa_output.pci-0000_00_1f.3.analog-stereo.monitor --file-format=wav test.wav

# ./a.out alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
# ./a.out alsa_output.pci-0000_00_1f.3.hdmi-stereo.monitor
# ./a.out alsa_input.pci-0000_00_1f.3.analog-stereo
./a.out bluez_sink.00_42_79_A4_D1_3D.a2dp_sink.monitor

# gdb --args ./a.out alsa_input.pci-0000_00_1f.3.analog-stereo
